import { motion } from 'framer-motion';
import { FileText, Scale, AlertTriangle, BookOpen, RefreshCw, Shield } from 'lucide-react';

const fadeIn = {
  hidden: { opacity: 0, y: 30 },
  visible: { opacity: 1, y: 0 },
};

const sections = [
  {
    icon: BookOpen,
    title: '1. Acceptance of Terms',
    content: [
      'By accessing and using LinguaReply AI ("the Service"), you accept and agree to be bound by these Terms and Conditions.',
      'If you do not agree with any part of these terms, you must not use the Service.',
      'These terms apply to all visitors, users, and others who access or use the Service.',
      'We reserve the right to modify these terms at any time. Your continued use of the Service after any changes indicates your acceptance of the new terms.',
    ],
  },
  {
    icon: Scale,
    title: '2. Use of the Service',
    content: [
      'LinguaReply AI provides AI-powered translation services including text translation, smart reply suggestions, voice input, and text-to-speech features.',
      'The Service is provided "as is" and is intended for personal and commercial use in accordance with these terms.',
      'You agree not to use the Service for any illegal or unauthorized purpose, including but not limited to translating content that is harmful, threatening, abusive, or otherwise objectionable.',
      'You are responsible for ensuring that your use of the Service complies with all applicable laws and regulations.',
      'We reserve the right to restrict or terminate access to the Service for users who violate these terms.',
    ],
  },
  {
    icon: AlertTriangle,
    title: '3. Limitations & Disclaimers',
    content: [
      'Translations are generated by AI and may not always be 100% accurate. We do not guarantee the accuracy, completeness, or reliability of any translation.',
      'The Service should not be relied upon for critical translations such as legal documents, medical information, or other high-stakes content without professional verification.',
      'We are not responsible for any loss, damage, or harm resulting from the use of translations provided by the Service.',
      'Smart reply suggestions are generated for convenience and may not always be contextually appropriate. Users should review suggestions before using them.',
      'Voice input and text-to-speech features depend on browser capabilities and may not work consistently across all devices and languages.',
    ],
  },
  {
    icon: Shield,
    title: '4. Intellectual Property',
    content: [
      'The LinguaReply AI platform, including its design, code, branding, and original content, is the intellectual property of LinguaReply AI and is protected by applicable copyright and trademark laws.',
      'Users retain ownership of the text they input for translation.',
      'Translated output generated by the Service may be used by the user for personal or commercial purposes.',
      'You may not reproduce, distribute, modify, or create derivative works from the Service\'s code, design, or branding without explicit written permission.',
    ],
  },
  {
    icon: RefreshCw,
    title: '5. Service Availability',
    content: [
      'We strive to provide uninterrupted service but cannot guarantee that the Service will be available at all times.',
      'We may experience hardware, software, or other problems, resulting in interruptions, delays, or errors.',
      'We reserve the right to change, modify, update, or discontinue the Service at any time without prior notice.',
      'We are not liable for any interruptions or errors in the Service that are beyond our reasonable control.',
    ],
  },
  {
    icon: FileText,
    title: '6. Changes to Terms',
    content: [
      'We reserve the right to update or modify these Terms and Conditions at any time without prior notice.',
      'Changes will be effective immediately upon posting to this page.',
      'The "Last updated" date at the top of this page indicates when these terms were last revised.',
      'Your continued use of the Service after any changes constitutes acceptance of the updated terms.',
      'We encourage you to review these terms periodically for any changes.',
    ],
  },
];

export default function Terms() {
  return (
    <main className="pt-24 pb-12">
      {/* Hero */}
      <section className="relative py-12 overflow-hidden">
        <div className="absolute inset-0 pointer-events-none">
          <div className="orb w-72 h-72 bg-accent-400 top-0 right-1/4" />
        </div>

        <div className="relative max-w-4xl mx-auto px-4 sm:px-6 lg:px-8 text-center">
          <motion.div initial="hidden" animate="visible" variants={fadeIn}>
            <div className="inline-flex items-center gap-2 px-4 py-2 rounded-full bg-primary-50 dark:bg-primary-900/30 border border-primary-200 dark:border-primary-800 mb-6">
              <FileText className="w-4 h-4 text-primary-500" />
              <span className="text-sm font-medium text-primary-700 dark:text-primary-300">
                Legal
              </span>
            </div>
            <h1 className="text-4xl sm:text-5xl font-bold text-slate-900 dark:text-white mb-4">
              Terms & <span className="gradient-text">Conditions</span>
            </h1>
            <p className="text-slate-500 dark:text-slate-400">
              Last updated: {new Date().toLocaleDateString('en-US', { month: 'long', day: 'numeric', year: 'numeric' })}
            </p>
          </motion.div>
        </div>
      </section>

      {/* Content */}
      <section className="py-12">
        <div className="max-w-3xl mx-auto px-4 sm:px-6 lg:px-8">
          <motion.div
            initial="hidden"
            animate="visible"
            variants={fadeIn}
            className="mb-10 p-6 rounded-2xl bg-amber-50 dark:bg-amber-900/20 border border-amber-200 dark:border-amber-800"
          >
            <p className="text-sm text-amber-700 dark:text-amber-300 leading-relaxed">
              Please read these Terms and Conditions carefully before using
              LinguaReply AI. By using the Service, you agree to be bound by
              these terms.
            </p>
          </motion.div>

          <div className="space-y-10">
            {sections.map((section, index) => (
              <motion.div
                key={section.title}
                initial="hidden"
                whileInView="visible"
                viewport={{ once: true }}
                variants={fadeIn}
                transition={{ delay: index * 0.05 }}
                className="scroll-mt-24"
              >
                <div className="flex items-center gap-3 mb-4">
                  <div className="p-2 rounded-lg bg-primary-50 dark:bg-primary-900/20">
                    <section.icon className="w-5 h-5 text-primary-500" />
                  </div>
                  <h2 className="text-xl font-bold text-slate-900 dark:text-white">
                    {section.title}
                  </h2>
                </div>
                <div className="space-y-3 pl-11">
                  {section.content.map((paragraph, pIndex) => (
                    <p
                      key={pIndex}
                      className="text-sm text-slate-500 dark:text-slate-400 leading-relaxed"
                    >
                      {paragraph}
                    </p>
                  ))}
                </div>
              </motion.div>
            ))}
          </div>

          <motion.div
            initial="hidden"
            whileInView="visible"
            viewport={{ once: true }}
            variants={fadeIn}
            className="mt-12 p-6 rounded-2xl bg-slate-50 dark:bg-slate-800/50 border border-slate-200 dark:border-slate-700"
          >
            <h3 className="text-base font-semibold text-slate-900 dark:text-white mb-3">
              Contact Us
            </h3>
            <p className="text-sm text-slate-500 dark:text-slate-400 leading-relaxed">
              If you have any questions about these Terms and Conditions, please
              contact us at hello@linguareply.ai or through our Contact page. We
              are happy to clarify any aspects of these terms.
            </p>
          </motion.div>
        </div>
      </section>
    </main>
  );
}
